#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.Reflection;
using UnityEditor;
using UnityEditor.Events;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.SceneManagement;
using UnityEngine.Tilemaps;

/// <summary>
/// SampleScene 用のギミック強化ステージ生成ツール v7。
/// 現在Scene内の Player の CapsuleCollider2D / Rigidbody2D / Player設定を読み取り、
/// 足場の高さ・幅・開始位置・説明文字サイズを実際のPlayer寸法から決める。
/// </summary>
public static class PlayableSampleStageBuilderV7
{
    private const string RootName = "AutoGeneratedStageV7";
    private const string OldRootName = "AutoGeneratedStageV6";
    private const string LegacyRootName = "AutoGeneratedStage";

    private const string FloorTag = "Floor";
    private const string WallTag = "Walls";

    private const float GroundTop = 0f;
    private const float GroundThickness = 1.0f;

    private const string EnemyPrefabPath = "Assets/Prefabs/Enemy.prefab";
    private const string EnemySpritePath = "Assets/image_/tekkyu_enemy.png";
    private const string BreakableWallPrefabPath = "Assets/Prefabs/Gimmicks/BreakableWall.prefab";
    private const string CheckpointPrefabPath = "Assets/Prefabs/Gimmicks/Checkpoint.prefab";
    private const string FallingPlatformPrefabPath = "Assets/Prefabs/Gimmicks/FallingPlatform.prefab";
    private const string DoorPrefabPath = "Assets/Prefabs/Gimmicks/GimmickDoor.prefab";
    private const string GoalPrefabPath = "Assets/Prefabs/Gimmicks/GoalPoint.prefab";
    private const string HitSwitchPrefabPath = "Assets/Prefabs/Gimmicks/HitSwitch.prefab";
    private const string MagnetPrefabPath = "Assets/Prefabs/Gimmicks/MagnetPoint.prefab";
    private const string MovingPlatformPrefabPath = "Assets/Prefabs/Gimmicks/MovingPlatform.prefab";
    private const string RespawnZonePrefabPath = "Assets/Prefabs/Gimmicks/RespawnZone.prefab";
    private const string SpikeTrapPrefabPath = "Assets/Prefabs/Gimmicks/SpikeTrap.prefab";
    private const string WeightSwitchPrefabPath = "Assets/Prefabs/Gimmicks/WeightSwitch.prefab";

    private const string TerrainSheetPath = "Assets/Pixel Adventure 1/Assets/Terrain/Terrain Sliced (16x16).png";
    private const string BoxPath = "Assets/Pixel Adventure 1/Assets/Items/Boxes/Box1/Idle.png";
    private const string BlockPath = "Assets/Pixel Adventure 1/Assets/Traps/Blocks/Idle.png";
    private const string WeightPlatePath = "Assets/Pixel Adventure 1/Assets/Traps/Platforms/Grey Off.png";
    private const string MovingPlatformPath = "Assets/Pixel Adventure 1/Assets/Traps/Platforms/Brown On (32x8).png";
    private const string FallingPlatformPath = "Assets/Pixel Adventure 1/Assets/Traps/Falling Platforms/On (32x10).png";
    private const string SpikePath = "Assets/Pixel Adventure 1/Assets/Traps/Spikes/Idle.png";
    private const string CheckpointPath = "Assets/Pixel Adventure 1/Assets/Items/Checkpoints/Checkpoint/Checkpoint (Flag Idle)(64x64).png";
    private const string GoalPath = "Assets/Pixel Adventure 1/Assets/Items/Checkpoints/End/End (Idle).png";
    private const string MagnetPath = "Assets/Pixel Adventure 1/Assets/Traps/Spiked Ball/Spiked Ball.png";

    private const string GeneratedTileFolder = "Assets/Generated/PlayableStageTilesV7";

    private static readonly List<TerrainRect> TerrainRects = new List<TerrainRect>();

    private static PlayerMetrics metrics;
    private static int terrainLayer;
    private static float cellSize = 0.16f;

    private static TileBase goldTop;
    private static TileBase goldFill;
    private static TileBase goldAccent;
    private static TileBase ruinTop;
    private static TileBase ruinFill;
    private static TileBase ruinAccent;
    private static TileBase spikeTile;

    [MenuItem("鉄球少女/SampleScene/ギミック強化ステージを生成（v7）")]
    private static void BuildStage()
    {
        if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
            return;

        Player player = UnityEngine.Object.FindAnyObjectByType<Player>(FindObjectsInactive.Exclude);
        if (player == null)
        {
            EditorUtility.DisplayDialog("Playerが見つかりません", "SampleScene内にPlayerを配置してから実行してください。", "OK");
            return;
        }

        if (!TryReadPlayerMetrics(player, out metrics))
        {
            EditorUtility.DisplayDialog("Player設定を読み取れません", "PlayerにCapsuleCollider2DとRigidbody2Dが必要です。", "OK");
            return;
        }

        if (!TryLoadAssets(out StageAssets assets) || !EnsureTiles())
            return;

        terrainLayer = LayerMask.NameToLayer(WallTag);
        if (terrainLayer < 0)
            terrainLayer = 0;

        RemoveRoot(RootName);
        RemoveRoot(OldRootName);
        RemoveRoot(LegacyRootName);
        DisableLegacyObjects();

        GameObject rootObject = new GameObject(RootName);
        Undo.RegisterCreatedObjectUndo(rootObject, "Generate playable stage v7");

        Transform geometryRoot = CreateGroup(rootObject.transform, "01_Geometry");
        Transform visualRoot = CreateGroup(rootObject.transform, "02_Visuals");
        Transform gimmickRoot = CreateGroup(rootObject.transform, "03_Gimmicks");
        Transform enemyRoot = CreateGroup(rootObject.transform, "04_Enemies");
        Transform guideRoot = CreateGroup(rootObject.transform, "05_Guides");
        Transform systemRoot = CreateGroup(rootObject.transform, "06_Systems");

        SetupPlayer(player, systemRoot, out Transform morningStar, out GimmickRespawnController respawn, out DeathRespawnManager deathRespawn);

        TerrainRects.Clear();
        BuildGeometry(geometryRoot);
        BuildTileVisuals(visualRoot);
        BuildHazards(gimmickRoot, assets, respawn);
        BuildGimmicks(gimmickRoot, assets, respawn, deathRespawn, morningStar);
        BuildEnemies(enemyRoot, assets);
        BuildGuides(guideRoot);
        ConfigureCameraBounds();

        Debug.Log(
            "[Stage v7] Player基準でギミック強化ステージを生成しました。"
            + $" Collider={metrics.width:F2} x {metrics.height:F2},"
            + $" 立ち位置Y={metrics.rootYOnGround:F2},"
            + $" 安全段差={metrics.safeStepHeight:F2},"
            + $" 推奨足場幅={metrics.safePlatformWidth:F2}");

        EditorSceneManager.MarkSceneDirty(SceneManager.GetActiveScene());
        Selection.activeGameObject = rootObject;
        SceneView.lastActiveSceneView?.FrameSelected();

        EditorUtility.DisplayDialog(
            "v7生成完了",
            "PlayerのCapsuleCollider2DとRigidbody2Dを読み取って生成しました。\n\n"
            + "・開始地点のめり込み補正\n"
            + "・動く床 / 落ちる床 / 磁力に落下リスクを追加\n"
            + "・磁力区画は下に地面がない必須ルート\n"
            + "・壊せる木箱の破片も木箱に統一\n"
            + "・文字はPlayerの高さ基準で大きく表示\n\n"
            + "保存してPlayで確認してください。",
            "OK");
    }

    [MenuItem("鉄球少女/SampleScene/v7ステージを削除")]
    private static void DeleteV6Stage()
    {
        RemoveRoot(RootName);
        EditorSceneManager.MarkSceneDirty(SceneManager.GetActiveScene());
    }

    // ---------------------------------------------------------------------
    // Player metrics
    // ---------------------------------------------------------------------

    private static bool TryReadPlayerMetrics(Player player, out PlayerMetrics result)
    {
        result = default;

        CapsuleCollider2D capsule = player.GetComponent<CapsuleCollider2D>();
        Rigidbody2D rb = player.GetComponent<Rigidbody2D>();
        if (capsule == null || rb == null)
            return false;

        float sx = Mathf.Abs(player.transform.lossyScale.x);
        float sy = Mathf.Abs(player.transform.lossyScale.y);

        result.width = capsule.size.x * sx;
        result.height = capsule.size.y * sy;
        result.footOffsetFromRoot = (capsule.offset.y - capsule.size.y * 0.5f) * sy;
        result.topOffsetFromRoot = (capsule.offset.y + capsule.size.y * 0.5f) * sy;
        result.rootYOnGround = GroundTop - result.footOffsetFromRoot + 0.06f;

        float jumpImpulse = ReadPrivateFloat(player, "_jumpSpeed", 7f);
        float gravity = Mathf.Abs(Physics2D.gravity.y) * Mathf.Max(0.01f, rb.gravityScale);
        float theoreticalJumpHeight = jumpImpulse * jumpImpulse / (2f * gravity);

        // 頭がぶつからず、慣性や入力ミスがあっても渡りやすい安全値。
        result.safeStepHeight = Mathf.Clamp(theoreticalJumpHeight * 0.32f, result.height * 0.18f, result.height * 0.30f);
        result.safePlatformWidth = Mathf.Max(result.width * 4.8f, 4.8f);
        result.guideCharacterSize = Mathf.Clamp(result.height * 0.060f, 0.16f, 0.22f);
        result.gateHeight = Mathf.Max(result.height * 1.05f, theoreticalJumpHeight * 1.20f);

        return result.width > 0.01f && result.height > 0.01f;
    }

    // ---------------------------------------------------------------------
    // Geometry
    // ---------------------------------------------------------------------

    private static void BuildGeometry(Transform root)
    {
        float step = metrics.safeStepHeight;
        float platform = metrics.safePlatformWidth;
        float gateHeight = metrics.gateHeight;
        float roofCenterY = gateHeight + metrics.height * 0.48f;
        const float roofHeight = 0.45f;

        // 1. 開始区画。ここだけは安全地帯として、操作の確認を行う。
        CreateFloor(root, "StartGround", -8f, 14.0f, GroundTop);
        CreateFloor(root, "StartPracticeStep", 7.1f, 7.1f + platform, step);

        // 2. 木箱を壊し、スイッチでドアを開く区画。
        CreateFloor(root, "BreakAndSwitchGround", 14.0f, 29.0f, GroundTop);
        CreateWall(root, "BreakRouteRoof", 14.7f, 25.4f, roofCenterY, roofHeight);

        // 3. 動く床の穴。床を待つか、上のビームに鉄球を当てて補助できる。
        CreateFloor(root, "MovingLeftBank", 29.0f, 32.0f, GroundTop);
        CreateFloor(root, "MovingRightBank", 38.2f, 46.0f, GroundTop);
        CreateWall(root, "MovingPracticeBeam", 33.1f, 37.2f, roofCenterY + 0.85f, roofHeight);

        // 4. 落ちる床の穴。落下前に右岸へ移動する。
        CreateFloor(root, "FallingLeftBank", 46.0f, 48.0f, GroundTop);
        CreateFloor(root, "FallingRightBank", 53.2f, 61.0f, GroundTop);

        // 5. 重量スイッチ。鉄球をプレートに残してドアを開ける。
        CreateFloor(root, "WeightGround", 61.0f, 74.6f, GroundTop);
        CreateWall(root, "WeightRouteRoof", 66.0f, 72.8f, roofCenterY, roofHeight);

        // 6. 磁力峡谷。下に地面はなく、2つの磁力点を使って渡る必須区画。
        //    左の発射台 -> 中継浮島 -> ゴール島。通常ジャンプだけでは届かない間隔にしている。
        CreateFloor(root, "MagnetLaunchLedge", 74.6f, 76.8f, step * 0.72f);
        CreateFloor(root, "MagnetRestIsland", 81.4f, 82.8f, step * 1.05f);
        CreateFloor(root, "GoalIsland", 87.0f, 99.0f, step * 0.72f);

        // ゴール奥の壁は見た目だけ。プレイヤーの進行は止めない。
        CreateWall(root, "GoalBackWall", 98.6f, 99.2f, step * 0.72f + 1.8f, 3.6f);
    }

    private static void BuildHazards(Transform root, StageAssets assets, GimmickRespawnController respawn)
    {
        // 失敗しても現在のチェックポイントへすぐ戻れるよう、危険区画の底だけにリスポーン帯を置く。
        CreateHazardBand(root, assets, respawn, "MovingGapHazard", 35.1f, 6.8f);
        CreateHazardBand(root, assets, respawn, "FallingGapHazard", 50.6f, 5.6f);
        CreateHazardBand(root, assets, respawn, "MagnetChasmHazard", 81.9f, 10.6f);
    }

    private static void CreateHazardBand(Transform parent, StageAssets assets, GimmickRespawnController respawn, string name, float centerX, float width)
    {
        GameObject spikes = Spawn(assets.spikeTrap, parent, name + "_Spikes", new Vector2(centerX, -1.15f));
        FitPrefabToWorldSize(spikes, LoadFirstSprite(SpikePath), new Vector2(width, 0.60f), Color.white);
        LinkUnityEvent(spikes.GetComponent<SpikeTrap>(), "onPlayerHit", respawn.Respawn);

        GameObject zone = Spawn(assets.respawnZone, parent, name + "_Respawn", new Vector2(centerX, -3.6f));
        SetBoxColliderWorldSize(zone, new Vector2(width + 1.0f, 2.8f));
        SetObjectReference(zone.GetComponent<RespawnZone>(), "gimmickRespawnController", respawn);
        HideBaseSprite(zone);
    }

    // ---------------------------------------------------------------------
    // Gimmicks
    // ---------------------------------------------------------------------

    private static void BuildGimmicks(
        Transform root,
        StageAssets assets,
        GimmickRespawnController respawn,
        DeathRespawnManager deathRespawn,
        Transform morningStar)
    {
        Sprite boxSprite = LoadFirstSprite(BoxPath);
        Sprite blockSprite = LoadFirstSprite(BlockPath);
        Sprite movingSprite = LoadFirstSprite(MovingPlatformPath);
        Sprite fallingSprite = LoadFirstSprite(FallingPlatformPath);
        Sprite weightSprite = LoadFirstSprite(WeightPlatePath);
        Sprite checkpointSprite = LoadFirstSprite(CheckpointPath);
        Sprite goalSprite = LoadFirstSprite(GoalPath);
        Sprite magnetSprite = LoadFirstSprite(MagnetPath);

        float gateHeight = metrics.gateHeight;
        float step = metrics.safeStepHeight;

        // 壊せる壁は2x2の木箱。破片も同じ木箱素材に統一する。
        GameObject woodFragmentTemplate = CreateWoodCrateFragmentTemplate(root, boxSprite);

        GameObject breakableBox = Spawn(
            assets.breakableWall,
            root,
            "BreakableCrateBarrier",
            new Vector2(16.8f, gateHeight * 0.5f));

        SetBoxColliderWorldSize(breakableBox, new Vector2(metrics.width * 2.15f, gateHeight));
        HideBaseSprite(breakableBox);
        CreateCrateStackVisual(
            breakableBox.transform,
            boxSprite,
            2,
            2,
            new Vector2(metrics.width * 1.98f, gateHeight * 0.92f));

        BreakableWall breakableWall = breakableBox.GetComponent<BreakableWall>();
        SetObjectReference(breakableWall, "fragmentPrefab", woodFragmentTemplate);
        SetInt(breakableWall, "fragmentCount", 7);
        SetFloat(breakableWall, "fragmentSpread", 0.45f);
        SetFloat(breakableWall, "minForce", 1.8f);
        SetFloat(breakableWall, "maxForce", 3.2f);

        // 壁の先で鉄球を当てるヒットスイッチ。
        GameObject hitSwitch = Spawn(assets.hitSwitch, root, "HitSwitch", new Vector2(21.0f, 0.62f));
        FitPrefabToWorldSize(hitSwitch, blockSprite, new Vector2(0.95f, 0.95f), new Color(1f, 0.50f, 0.20f, 1f));

        GameObject hitDoor = Spawn(assets.door, root, "HitDoor", new Vector2(24.3f, gateHeight * 0.5f));
        FitPrefabToWorldSize(hitDoor, blockSprite, new Vector2(metrics.width * 1.35f, gateHeight), new Color(0.95f, 0.25f, 0.24f, 1f));
        ConfigureDoorStartsOpen(hitDoor.GetComponent<GimmickDoor>(), false);
        ConfigureHitSwitch(hitSwitch.GetComponent<HitSwitch>(), hitDoor.GetComponent<GimmickDoor>());

        GameObject checkpointA = Spawn(assets.checkpoint, root, "Checkpoint_AfterDoor", new Vector2(27.5f, 0.90f));
        FitPrefabToWorldSize(checkpointA, checkpointSprite, new Vector2(1.0f, 1.55f), Color.white);
        ConfigureCheckpoint(checkpointA.GetComponent<Checkpoint>(), respawn, deathRespawn);

        // 動く床は両岸へ重なる位置を往復する。
        GameObject movingPlatform = Spawn(assets.movingPlatform, root, "MovingPlatform", new Vector2(33.9f, 0.28f));
        FitPrefabToWorldSize(movingPlatform, movingSprite, new Vector2(4.8f, 0.56f), Color.white);
        ConfigureMovingPlatform(movingPlatform.GetComponent<MovingPlatform>(), new Vector2(3.6f, 0f), 1.25f, 1.0f);

        // 落ちる床は渡り切れる時間を残すが、立ち止まると危険。
        GameObject fallingPlatform = Spawn(assets.fallingPlatform, root, "FallingPlatform", new Vector2(50.5f, 0.31f));
        FitPrefabToWorldSize(fallingPlatform, fallingSprite, new Vector2(4.4f, 0.62f), Color.white);
        ConfigureFallingPlatform(fallingPlatform.GetComponent<FallingPlatform>(), 1.35f, 3.0f);

        // 重量スイッチ。ドアは一度開けば閉じない。
        GameObject weightSwitch = Spawn(assets.weightSwitch, root, "WeightSwitch", new Vector2(64.4f, 0.24f));
        FitPrefabToWorldSize(weightSwitch, weightSprite, new Vector2(3.4f, 0.48f), new Color(0.70f, 0.90f, 1f, 1f));

        GameObject weightDoor = Spawn(assets.door, root, "WeightDoor", new Vector2(69.2f, gateHeight * 0.5f));
        FitPrefabToWorldSize(weightDoor, blockSprite, new Vector2(metrics.width * 1.35f, gateHeight), new Color(0.30f, 0.68f, 1f, 1f));
        ConfigureDoorStartsOpen(weightDoor.GetComponent<GimmickDoor>(), false);
        ConfigureWeightSwitch(weightSwitch.GetComponent<WeightSwitch>(), weightDoor.GetComponent<GimmickDoor>());

        GameObject checkpointB = Spawn(assets.checkpoint, root, "Checkpoint_BeforeMagnetChasm", new Vector2(73.3f, 0.90f));
        FitPrefabToWorldSize(checkpointB, checkpointSprite, new Vector2(1.0f, 1.55f), Color.white);
        ConfigureCheckpoint(checkpointB.GetComponent<Checkpoint>(), respawn, deathRespawn);

        // 磁力峡谷。鉄球が磁力点に入っている間、Playerにも短い磁力ダッシュを与える。
        // MagnetPoint.cs の「Traversal Assist」を有効にしている。
        GameObject magnetA = Spawn(assets.magnet, root, "MagnetPoint_A", new Vector2(79.25f, step * 0.72f + 3.10f));
        FitPrefabToWorldSize(magnetA, magnetSprite, new Vector2(1.22f, 1.22f), new Color(0.20f, 0.90f, 1f, 1f));
        ConfigureCircleColliderWorldRadius(magnetA.GetComponent<CircleCollider2D>(), magnetA.transform, 2.0f);
        ConfigureMagnetTraversal(magnetA.GetComponent<MagnetPoint>(), 68f, 13f, 0.85f);

        GameObject magnetB = Spawn(assets.magnet, root, "MagnetPoint_B", new Vector2(84.45f, step * 1.05f + 3.10f));
        FitPrefabToWorldSize(magnetB, magnetSprite, new Vector2(1.22f, 1.22f), new Color(0.20f, 0.90f, 1f, 1f));
        ConfigureCircleColliderWorldRadius(magnetB.GetComponent<CircleCollider2D>(), magnetB.transform, 2.0f);
        ConfigureMagnetTraversal(magnetB.GetComponent<MagnetPoint>(), 68f, 13f, 0.85f);

        GameObject goal = Spawn(assets.goal, root, "Goal", new Vector2(94.1f, step * 0.72f + 1.05f));
        FitPrefabToWorldSize(goal, goalSprite, new Vector2(1.55f, 1.90f), Color.white);
        ConfigureGoal(goal.GetComponent<GoalPoint>(), morningStar);
    }

    private static void BuildEnemies(Transform root, StageAssets assets)
    {
        // 敵は入力練習と終盤の足場確認にだけ置き、ギミックの真横には置かない。
        SpawnEnemy(root, assets.enemy, "Enemy_StartPractice", new Vector2(10.5f, 0.55f), 2.3f);
        SpawnEnemy(root, assets.enemy, "Enemy_AfterMovingGap", new Vector2(41.9f, 0.55f), 2.3f);
        SpawnEnemy(root, assets.enemy, "Enemy_GoalIsland", new Vector2(90.0f, metrics.safeStepHeight * 0.72f + 0.55f), 2.3f);
    }

    // ---------------------------------------------------------------------
    // Guides
    // ---------------------------------------------------------------------

    private static void BuildGuides(Transform root)
    {
        float s = metrics.guideCharacterSize;
        float high = metrics.height + 1.80f;
        float step = metrics.safeStepHeight;

        CreateGuide(root, "Guide_Start", new Vector2(2.6f, high), "A / D で移動\nSpaceでジャンプ", s);
        CreateGuide(root, "Guide_Crate", new Vector2(16.8f, metrics.gateHeight + 1.18f), "鉄球で\n木箱をこわす", s * 0.96f);
        CreateGuide(root, "Guide_Hit", new Vector2(21.0f, 2.72f), "鉄球でON", s);
        CreateGuide(root, "Guide_Moving", new Vector2(35.1f, 3.00f), "動く床\n落ちたら戻る", s * 0.94f);
        CreateGuide(root, "Guide_Falling", new Vector2(50.6f, 3.00f), "乗ると落ちる\n急いで渡る", s * 0.90f);
        CreateGuide(root, "Guide_Weight", new Vector2(64.4f, 3.00f), "鉄球を\nのせる", s);
        CreateGuide(root, "Guide_MagnetA", new Vector2(79.25f, step * 0.72f + 5.08f), "鉄球を磁力点へ\n引っ張られて渡る", s * 0.92f);
        CreateGuide(root, "Guide_MagnetB", new Vector2(84.45f, step * 1.05f + 4.98f), "次の磁力点へ", s * 0.90f);
        CreateGuide(root, "Guide_Goal", new Vector2(94.2f, step * 0.72f + 3.55f), "GOAL", s * 1.18f);
    }

    // ---------------------------------------------------------------------
    // Tilemap visuals
    // ---------------------------------------------------------------------

    private static bool EnsureTiles()
    {
        UnityEngine.Object[] terrainAssets = AssetDatabase.LoadAllAssetsAtPath(TerrainSheetPath);
        if (terrainAssets == null || terrainAssets.Length == 0)
        {
            EditorUtility.DisplayDialog("Terrain素材がありません", TerrainSheetPath + " が見つかりません。", "OK");
            return false;
        }

        Sprite goldTopSprite = FindSprite(terrainAssets, "Terrain (16x16)_112");
        Sprite goldFillSprite = FindSprite(terrainAssets, "Terrain (16x16)_111");
        Sprite goldAccentSprite = FindSprite(terrainAssets, "Terrain (16x16)_113");
        Sprite ruinTopSprite = FindSprite(terrainAssets, "Terrain (16x16)_106");
        Sprite ruinFillSprite = FindSprite(terrainAssets, "Terrain (16x16)_107");
        Sprite ruinAccentSprite = FindSprite(terrainAssets, "Terrain (16x16)_108");
        Sprite spikeSprite = LoadFirstSprite(SpikePath);

        if (goldTopSprite == null || goldFillSprite == null || goldAccentSprite == null ||
            ruinTopSprite == null || ruinFillSprite == null || ruinAccentSprite == null || spikeSprite == null)
        {
            EditorUtility.DisplayDialog("Tile素材が不足しています", "Pixel AdventureのSprite分割・素材名を確認してください。", "OK");
            return false;
        }

        EnsureFolder("Assets/Generated");
        EnsureFolder(GeneratedTileFolder);

        goldTop = LoadOrCreateTile(GeneratedTileFolder + "/GoldTop.asset", goldTopSprite);
        goldFill = LoadOrCreateTile(GeneratedTileFolder + "/GoldFill.asset", goldFillSprite);
        goldAccent = LoadOrCreateTile(GeneratedTileFolder + "/GoldAccent.asset", goldAccentSprite);
        ruinTop = LoadOrCreateTile(GeneratedTileFolder + "/RuinTop.asset", ruinTopSprite);
        ruinFill = LoadOrCreateTile(GeneratedTileFolder + "/RuinFill.asset", ruinFillSprite);
        ruinAccent = LoadOrCreateTile(GeneratedTileFolder + "/RuinAccent.asset", ruinAccentSprite);
        spikeTile = LoadOrCreateTile(GeneratedTileFolder + "/Spikes.asset", spikeSprite);

        cellSize = goldFillSprite.bounds.size.x;
        if (cellSize <= 0.0001f)
            cellSize = 0.16f;

        AssetDatabase.SaveAssets();
        return true;
    }

    private static void BuildTileVisuals(Transform root)
    {
        GameObject gridObject = new GameObject("PixelAdventureGrid");
        gridObject.transform.SetParent(root);
        gridObject.transform.position = new Vector3(0f, 0f, -0.18f);

        Grid grid = gridObject.AddComponent<Grid>();
        grid.cellSize = new Vector3(cellSize, cellSize, 1f);

        Tilemap platformMap = CreateTilemap(gridObject.transform, "GoldPlatforms", -10);
        Tilemap wallMap = CreateTilemap(gridObject.transform, "OrangeWalls", -9);

        foreach (TerrainRect rect in TerrainRects)
            PaintTerrain(rect, rect.isWall ? wallMap : platformMap);
    }

    private static Tilemap CreateTilemap(Transform parent, string name, int order)
    {
        GameObject mapObject = new GameObject(name);
        mapObject.transform.SetParent(parent);

        Tilemap map = mapObject.AddComponent<Tilemap>();
        TilemapRenderer renderer = mapObject.AddComponent<TilemapRenderer>();
        renderer.sortingOrder = order;
        return map;
    }

    private static void PaintTerrain(TerrainRect rect, Tilemap map)
    {
        int width = Mathf.Max(1, Mathf.RoundToInt(rect.size.x / cellSize));
        int height = Mathf.Max(1, Mathf.RoundToInt(rect.size.y / cellSize));
        int minX = Mathf.RoundToInt((rect.center.x - rect.size.x * 0.5f) / cellSize);
        int minY = Mathf.RoundToInt((rect.center.y - rect.size.y * 0.5f) / cellSize);

        for (int y = 0; y < height; y++)
        {
            bool isTop = y == height - 1;
            for (int x = 0; x < width; x++)
            {
                TileBase tile;
                if (rect.isWall)
                {
                    tile = isTop ? ruinTop : ruinFill;
                    if (!isTop && (x + y * 3) % 12 == 0)
                        tile = ruinAccent;
                }
                else
                {
                    tile = isTop ? goldTop : goldFill;
                    if (!isTop && (x + y * 5) % 17 == 0)
                        tile = goldAccent;
                }

                map.SetTile(new Vector3Int(minX + x, minY + y, 0), tile);
            }
        }
    }

    // ---------------------------------------------------------------------
    // Geometry helpers
    // ---------------------------------------------------------------------

    private static void CreateFloor(Transform parent, string name, float left, float right, float topY)
    {
        float width = Mathf.Max(0.2f, right - left);
        CreateSolid(parent, name, new Vector2((left + right) * 0.5f, topY - GroundThickness * 0.5f), new Vector2(width, GroundThickness), FloorTag, false);
    }

    private static void CreateWall(Transform parent, string name, float left, float right, float centerY, float height)
    {
        float width = Mathf.Max(0.2f, right - left);
        CreateSolid(parent, name, new Vector2((left + right) * 0.5f, centerY), new Vector2(width, height), WallTag, true);
    }

    private static void CreateSolid(Transform parent, string name, Vector2 center, Vector2 size, string tagName, bool isWall)
    {
        GameObject block = new GameObject(name);
        block.transform.SetParent(parent);
        block.transform.position = new Vector3(center.x, center.y, 0f);
        block.layer = terrainLayer;
        block.tag = tagName;

        BoxCollider2D collider = block.AddComponent<BoxCollider2D>();
        collider.size = size;

        TerrainRects.Add(new TerrainRect(center, size, isWall));
    }

    // ---------------------------------------------------------------------
    // Player / respawn / camera
    // ---------------------------------------------------------------------

    private static void SetupPlayer(
        Player player,
        Transform systemRoot,
        out Transform morningStar,
        out GimmickRespawnController respawn,
        out DeathRespawnManager deathRespawn)
    {
        Vector3 spawn = new Vector3(2.5f, metrics.rootYOnGround, 0f);
        player.transform.position = spawn;

        Rigidbody2D playerRb = player.GetComponent<Rigidbody2D>();
        if (playerRb != null)
        {
            playerRb.linearVelocity = Vector2.zero;
            playerRb.angularVelocity = 0f;
        }

        GameObject ball = FindGameObjectWithTagSafely("morningstar");
        morningStar = ball != null ? ball.transform : null;
        if (morningStar != null)
        {
            morningStar.position = spawn + new Vector3(-metrics.width * 1.45f, 0f, 0f);
            Rigidbody2D ballRb = morningStar.GetComponent<Rigidbody2D>();
            if (ballRb != null)
            {
                ballRb.linearVelocity = Vector2.zero;
                ballRb.angularVelocity = 0f;
            }
        }

        GameObject spawnObject = new GameObject("InitialSpawn");
        spawnObject.transform.SetParent(systemRoot);
        spawnObject.transform.position = spawn;

        deathRespawn = UnityEngine.Object.FindAnyObjectByType<DeathRespawnManager>(FindObjectsInactive.Exclude);
        if (deathRespawn != null)
        {
            SetObjectReference(deathRespawn, "_defaultSpawnPoint", spawnObject.transform);
            SetObjectReference(deathRespawn, "_player", player);
            SetObjectReference(deathRespawn, "_playerHealth", player.GetComponent<PlayerHealth>());
        }

        GameObject respawnObject = new GameObject("GimmickRespawnController");
        respawnObject.transform.SetParent(systemRoot);
        respawn = respawnObject.AddComponent<GimmickRespawnController>();
        SetObjectReference(respawn, "player", player.transform);
        SetObjectReference(respawn, "playerRigidbody", playerRb);
        SetObjectReference(respawn, "initialRespawnPoint", spawnObject.transform);
        SetObjectReference(respawn, "morningstar", morningStar);
        SetObjectReference(respawn, "morningstarRigidbody", morningStar != null ? morningStar.GetComponent<Rigidbody2D>() : null);
        SetVector2(respawn, "morningstarOffset", new Vector2(-metrics.width * 1.45f, 0f));
    }

    private static void ConfigureCameraBounds()
    {
        CameraFollow cameraFollow = UnityEngine.Object.FindAnyObjectByType<CameraFollow>(FindObjectsInactive.Exclude);
        if (cameraFollow == null)
            return;

        SetBool(cameraFollow, "_useBounds", true);
        SetFloat(cameraFollow, "_minX", 5.5f);
        SetFloat(cameraFollow, "_maxX", 93.0f);
        SetFloat(cameraFollow, "_minY", 3.4f);
        SetFloat(cameraFollow, "_maxY", 6.6f);
    }

    private static void ConfigureCheckpoint(Checkpoint checkpoint, GimmickRespawnController respawn, DeathRespawnManager deathRespawn)
    {
        if (checkpoint == null)
            return;

        SetObjectReference(checkpoint, "gimmickRespawnController", respawn);
        SetObjectReference(checkpoint, "deathRespawnManager", deathRespawn);
        SetObjectReference(checkpoint, "respawnPoint", checkpoint.transform);
    }

    private static void ConfigureGoal(GoalPoint goal, Transform morningStar)
    {
        if (goal == null)
            return;

        SetBool(goal, "requireMorningStarNearby", false);
        SetObjectReference(goal, "morningStar", morningStar);
        SetBool(goal, "showDebugLog", true);
    }

    // ---------------------------------------------------------------------
    // Gimmick setup
    // ---------------------------------------------------------------------

    private static void ConfigureHitSwitch(HitSwitch hitSwitch, GimmickDoor door)
    {
        if (hitSwitch == null || door == null)
            return;

        SetFloat(hitSwitch, "activeDuration", 60f);
        SetBool(hitSwitch, "flashBeforeOff", false);
        LinkUnityEvent(hitSwitch, "onHit", door.Open);
    }

    private static void ConfigureWeightSwitch(WeightSwitch weightSwitch, GimmickDoor door)
    {
        if (weightSwitch == null || door == null)
            return;

        LinkUnityEvent(weightSwitch, "onPressed", door.Open);
        // onReleasedにはCloseを登録しない。1回開いたら進行不能にならない。
    }

    private static void ConfigureDoorStartsOpen(GimmickDoor door, bool startsOpen)
    {
        if (door != null)
            SetBool(door, "startsOpen", startsOpen);
    }

    private static void ConfigureMovingPlatform(MovingPlatform platform, Vector2 offset, float speed, float wait)
    {
        if (platform == null)
            return;

        SetVector2(platform, "moveOffset", offset);
        SetFloat(platform, "moveSpeed", speed);
        SetFloat(platform, "waitTimeAtEnds", wait);
    }

    private static void ConfigureFallingPlatform(FallingPlatform platform, float fallDelay, float respawnDelay)
    {
        if (platform == null)
            return;

        SetFloat(platform, "fallDelay", fallDelay);
        SetFloat(platform, "respawnDelay", respawnDelay);
    }

    private static void ConfigureMagnetTraversal(MagnetPoint magnet, float playerPullForce, float playerMaxPullSpeed, float releaseDistance)
    {
        if (magnet == null)
            return;

        SetFloat(magnet, "attractionForce", 45f);
        SetFloat(magnet, "maxAttractSpeed", 14f);
        SetFloat(magnet, "snapDistance", 0.30f);
        SetBool(magnet, "pullPlayerWhileBallAttached", true);
        SetFloat(magnet, "playerPullForce", playerPullForce);
        SetFloat(magnet, "playerMaxPullSpeed", playerMaxPullSpeed);
        SetFloat(magnet, "playerReleaseDistance", releaseDistance);
    }

    // ---------------------------------------------------------------------
    // Visual helpers
    // ---------------------------------------------------------------------

    private static void FitPrefabToWorldSize(GameObject target, Sprite sprite, Vector2 desiredWorldSize, Color tint)
    {
        if (target == null || sprite == null)
            return;

        SpriteRenderer renderer = target.GetComponent<SpriteRenderer>();
        if (renderer == null)
            return;

        BoxCollider2D box = target.GetComponent<BoxCollider2D>();
        Vector2 sourceSize = sprite.bounds.size;
        if (sourceSize.x <= 0.0001f || sourceSize.y <= 0.0001f)
            return;

        target.transform.localScale = new Vector3(desiredWorldSize.x / sourceSize.x, desiredWorldSize.y / sourceSize.y, 1f);

        renderer.sprite = sprite;
        renderer.color = tint;
        renderer.enabled = true;
        renderer.drawMode = SpriteDrawMode.Simple;
        renderer.sortingOrder = 5;

        if (box != null)
        {
            box.size = sourceSize;
            box.offset = Vector2.zero;
        }
    }

    private static void SetBoxColliderWorldSize(GameObject target, Vector2 desiredWorldSize)
    {
        if (target == null)
            return;

        BoxCollider2D box = target.GetComponent<BoxCollider2D>();
        if (box == null)
            return;

        float baseWidth = Mathf.Max(0.0001f, box.size.x * Mathf.Abs(target.transform.localScale.x));
        float baseHeight = Mathf.Max(0.0001f, box.size.y * Mathf.Abs(target.transform.localScale.y));

        target.transform.localScale = new Vector3(
            target.transform.localScale.x * (desiredWorldSize.x / baseWidth),
            target.transform.localScale.y * (desiredWorldSize.y / baseHeight),
            1f);

        box.offset = Vector2.zero;
    }

    private static void ConfigureCircleColliderWorldRadius(CircleCollider2D circle, Transform target, float radius)
    {
        if (circle == null || target == null)
            return;

        float scale = Mathf.Max(0.0001f, Mathf.Abs(target.lossyScale.x));
        circle.radius = radius / scale;
        circle.offset = Vector2.zero;
    }

    private static void CreateCrateStackVisual(Transform parent, Sprite crateSprite, int columns, int rows, Vector2 totalWorldSize)
    {
        if (parent == null || crateSprite == null)
            return;

        Vector2 spriteSize = crateSprite.bounds.size;
        Vector3 parentScale = parent.lossyScale;
        if (spriteSize.x <= 0.0001f || spriteSize.y <= 0.0001f ||
            Mathf.Abs(parentScale.x) <= 0.0001f || Mathf.Abs(parentScale.y) <= 0.0001f)
            return;

        for (int y = 0; y < rows; y++)
        {
            for (int x = 0; x < columns; x++)
            {
                float worldX = ((x + 0.5f) / columns - 0.5f) * totalWorldSize.x;
                float worldY = ((y + 0.5f) / rows - 0.5f) * totalWorldSize.y;

                GameObject crate = new GameObject("CrateVisual");
                crate.transform.SetParent(parent);
                crate.transform.localPosition = new Vector3(worldX / parentScale.x, worldY / parentScale.y, -0.05f);

                float wantedWidth = totalWorldSize.x / columns * 0.90f;
                float wantedHeight = totalWorldSize.y / rows * 0.90f;
                crate.transform.localScale = new Vector3(
                    wantedWidth / spriteSize.x / parentScale.x,
                    wantedHeight / spriteSize.y / parentScale.y,
                    1f);

                SpriteRenderer renderer = crate.AddComponent<SpriteRenderer>();
                renderer.sprite = crateSprite;
                renderer.color = Color.white;
                renderer.sortingOrder = 6;
            }
        }
    }

    private static GameObject CreateWoodCrateFragmentTemplate(Transform parent, Sprite crateSprite)
    {
        GameObject template = new GameObject("WoodCrateFragmentTemplate");
        template.transform.SetParent(parent);
        template.transform.position = new Vector3(-1000f, -1000f, 0f);

        SpriteRenderer renderer = template.AddComponent<SpriteRenderer>();
        renderer.sprite = crateSprite;
        renderer.sortingOrder = 6;

        Rigidbody2D rigidbody = template.AddComponent<Rigidbody2D>();
        rigidbody.gravityScale = 2.2f;
        rigidbody.mass = 0.12f;
        rigidbody.collisionDetectionMode = CollisionDetectionMode2D.Continuous;

        BoxCollider2D collider = template.AddComponent<BoxCollider2D>();
        collider.size = crateSprite != null ? crateSprite.bounds.size : Vector2.one;

        if (crateSprite != null)
        {
            Vector2 sourceSize = crateSprite.bounds.size;
            float desiredSize = 0.30f;
            if (sourceSize.x > 0.0001f && sourceSize.y > 0.0001f)
            {
                template.transform.localScale = new Vector3(
                    desiredSize / sourceSize.x,
                    desiredSize / sourceSize.y,
                    1f);
            }
        }

        return template;
    }

    private static void HideBaseSprite(GameObject target)
    {
        if (target == null)
            return;

        SpriteRenderer renderer = target.GetComponent<SpriteRenderer>();
        if (renderer != null)
            renderer.enabled = false;
    }

    private static void CreateGuide(Transform parent, string name, Vector2 position, string text, float characterSize)
    {
        GameObject guide = new GameObject(name);
        guide.transform.SetParent(parent);
        guide.transform.position = new Vector3(position.x, position.y, -0.45f);

        TextMesh shadow = MakeText(guide.transform, "Shadow", text, characterSize, new Color(0.06f, 0.10f, 0.20f, 0.85f));
        shadow.transform.localPosition = new Vector3(0.035f, -0.035f, 0.01f);
        shadow.GetComponent<MeshRenderer>().sortingOrder = 30;

        TextMesh main = MakeText(guide.transform, "Text", text, characterSize, Color.white);
        main.GetComponent<MeshRenderer>().sortingOrder = 31;
    }

    private static TextMesh MakeText(Transform parent, string name, string text, float characterSize, Color color)
    {
        GameObject objectText = new GameObject(name);
        objectText.transform.SetParent(parent);
        objectText.transform.localPosition = Vector3.zero;

        TextMesh mesh = objectText.AddComponent<TextMesh>();
        mesh.text = text;
        mesh.characterSize = characterSize;
        mesh.fontSize = 42;
        mesh.lineSpacing = 0.86f;
        mesh.anchor = TextAnchor.MiddleCenter;
        mesh.alignment = TextAlignment.Center;
        mesh.fontStyle = FontStyle.Bold;
        mesh.color = color;
        return mesh;
    }

    // ---------------------------------------------------------------------
    // Asset / serialized helpers
    // ---------------------------------------------------------------------

    private static bool TryLoadAssets(out StageAssets assets)
    {
        assets = new StageAssets
        {
            enemy = LoadPrefab(EnemyPrefabPath),
            breakableWall = LoadPrefab(BreakableWallPrefabPath),
            checkpoint = LoadPrefab(CheckpointPrefabPath),
            fallingPlatform = LoadPrefab(FallingPlatformPrefabPath),
            door = LoadPrefab(DoorPrefabPath),
            goal = LoadPrefab(GoalPrefabPath),
            hitSwitch = LoadPrefab(HitSwitchPrefabPath),
            magnet = LoadPrefab(MagnetPrefabPath),
            movingPlatform = LoadPrefab(MovingPlatformPrefabPath),
            respawnZone = LoadPrefab(RespawnZonePrefabPath),
            spikeTrap = LoadPrefab(SpikeTrapPrefabPath),
            weightSwitch = LoadPrefab(WeightSwitchPrefabPath)
        };

        if (assets.IsComplete)
            return true;

        EditorUtility.DisplayDialog("Prefabが不足しています", "Assets/Prefabs/Gimmicks のPrefabを確認してください。", "OK");
        return false;
    }

    private static GameObject LoadPrefab(string path)
    {
        GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);
        if (prefab == null)
            Debug.LogWarning("Prefab not found: " + path);
        return prefab;
    }

    private static Sprite LoadFirstSprite(string path)
    {
        UnityEngine.Object[] objects = AssetDatabase.LoadAllAssetsAtPath(path);
        foreach (UnityEngine.Object obj in objects)
        {
            if (obj is Sprite sprite)
                return sprite;
        }

        return AssetDatabase.LoadAssetAtPath<Sprite>(path);
    }

    private static Sprite FindSprite(UnityEngine.Object[] assets, string name)
    {
        foreach (UnityEngine.Object asset in assets)
        {
            if (asset is Sprite sprite && sprite.name == name)
                return sprite;
        }

        return null;
    }

    private static Tile LoadOrCreateTile(string path, Sprite sprite)
    {
        Tile tile = AssetDatabase.LoadAssetAtPath<Tile>(path);
        if (tile == null)
        {
            tile = ScriptableObject.CreateInstance<Tile>();
            tile.name = System.IO.Path.GetFileNameWithoutExtension(path);
            AssetDatabase.CreateAsset(tile, path);
        }

        tile.sprite = sprite;
        tile.colliderType = Tile.ColliderType.None;
        EditorUtility.SetDirty(tile);
        return tile;
    }

    private static void EnsureFolder(string folderPath)
    {
        if (AssetDatabase.IsValidFolder(folderPath))
            return;

        string[] parts = folderPath.Split('/');
        string current = parts[0];

        for (int i = 1; i < parts.Length; i++)
        {
            string next = current + "/" + parts[i];
            if (!AssetDatabase.IsValidFolder(next))
                AssetDatabase.CreateFolder(current, parts[i]);
            current = next;
        }
    }

    private static GameObject Spawn(GameObject prefab, Transform parent, string name, Vector2 position)
    {
        GameObject instance = (GameObject)PrefabUtility.InstantiatePrefab(prefab);
        instance.name = name;
        instance.transform.SetParent(parent);
        instance.transform.position = new Vector3(position.x, position.y, 0f);
        instance.transform.rotation = Quaternion.identity;
        return instance;
    }

    private static void SpawnEnemy(Transform parent, GameObject prefab, string name, Vector2 position, float _)
    {
        GameObject enemy = Spawn(prefab, parent, name, position);

        Sprite enemySprite = LoadFirstSprite(EnemySpritePath);
        SpriteRenderer renderer = enemy.GetComponent<SpriteRenderer>();
        BoxCollider2D collider = enemy.GetComponent<BoxCollider2D>();

        float desiredHeight = Mathf.Clamp(metrics.height * 0.56f, 1.25f, 1.90f);
        float spriteScale = desiredHeight / Mathf.Max(0.0001f, enemySprite != null ? enemySprite.bounds.size.y : 1f);
        enemy.transform.localScale = new Vector3(spriteScale, spriteScale, 1f);

        if (renderer != null && enemySprite != null)
        {
            renderer.sprite = enemySprite;
            renderer.color = Color.white;
            renderer.sortingOrder = 6;
        }

        if (collider != null)
        {
            collider.size = new Vector2(0.90f / spriteScale, 1.08f / spriteScale);
            collider.offset = new Vector2(0f, -0.04f / spriteScale);
        }

        int layer = LayerMask.NameToLayer("Enemy");
        if (layer >= 0)
            enemy.layer = layer;
    }

    private static Transform CreateGroup(Transform parent, string name)
    {
        GameObject group = new GameObject(name);
        group.transform.SetParent(parent);
        return group.transform;
    }

    private static void LinkUnityEvent(Component owner, string fieldName, UnityAction action)
    {
        if (owner == null)
            return;

        FieldInfo field = owner.GetType().GetField(fieldName, BindingFlags.Instance | BindingFlags.NonPublic);
        if (field == null || !typeof(UnityEvent).IsAssignableFrom(field.FieldType))
        {
            Debug.LogWarning(owner.GetType().Name + "." + fieldName + " was not found.", owner);
            return;
        }

        UnityEvent unityEvent = field.GetValue(owner) as UnityEvent;
        if (unityEvent == null)
        {
            unityEvent = new UnityEvent();
            field.SetValue(owner, unityEvent);
        }

        while (unityEvent.GetPersistentEventCount() > 0)
            UnityEventTools.RemovePersistentListener(unityEvent, 0);

        UnityEventTools.AddPersistentListener(unityEvent, action);
        EditorUtility.SetDirty(owner);
    }

    private static void SetObjectReference(UnityEngine.Object target, string fieldName, UnityEngine.Object value)
    {
        SetSerialized(target, fieldName, property => property.objectReferenceValue = value);
    }

    private static void SetBool(UnityEngine.Object target, string fieldName, bool value)
    {
        SetSerialized(target, fieldName, property => property.boolValue = value);
    }

    private static void SetFloat(UnityEngine.Object target, string fieldName, float value)
    {
        SetSerialized(target, fieldName, property => property.floatValue = value);
    }

    private static void SetInt(UnityEngine.Object target, string fieldName, int value)
    {
        SetSerialized(target, fieldName, property => property.intValue = value);
    }

    private static void SetVector2(UnityEngine.Object target, string fieldName, Vector2 value)
    {
        SetSerialized(target, fieldName, property => property.vector2Value = value);
    }

    private static void SetSerialized(UnityEngine.Object target, string fieldName, Action<SerializedProperty> write)
    {
        if (target == null)
            return;

        SerializedObject serialized = new SerializedObject(target);
        SerializedProperty property = serialized.FindProperty(fieldName);
        if (property == null)
        {
            Debug.LogWarning(target.GetType().Name + "." + fieldName + " was not found.", target);
            return;
        }

        write(property);
        serialized.ApplyModifiedPropertiesWithoutUndo();
        EditorUtility.SetDirty(target);
    }

    private static float ReadPrivateFloat(UnityEngine.Object target, string fieldName, float fallback)
    {
        if (target == null)
            return fallback;

        SerializedObject serialized = new SerializedObject(target);
        SerializedProperty property = serialized.FindProperty(fieldName);
        return property != null ? property.floatValue : fallback;
    }

    private static GameObject FindGameObjectWithTagSafely(string tag)
    {
        try
        {
            return GameObject.FindGameObjectWithTag(tag);
        }
        catch (UnityException)
        {
            return null;
        }
    }

    private static void RemoveRoot(string name)
    {
        GameObject root = GameObject.Find(name);
        if (root != null)
            Undo.DestroyObjectImmediate(root);
    }

    private static void DisableLegacyObjects()
    {
        string[] names = { "floor", "wall", "Enemy", "CheckpointA", "CheckpointB", "Goal", "GoalPoint" };

        foreach (string name in names)
        {
            GameObject objectToDisable = GameObject.Find(name);
            if (objectToDisable == null)
                continue;

            objectToDisable.SetActive(false);
        }
    }

    private struct TerrainRect
    {
        public readonly Vector2 center;
        public readonly Vector2 size;
        public readonly bool isWall;

        public TerrainRect(Vector2 center, Vector2 size, bool isWall)
        {
            this.center = center;
            this.size = size;
            this.isWall = isWall;
        }
    }

    private struct PlayerMetrics
    {
        public float width;
        public float height;
        public float footOffsetFromRoot;
        public float topOffsetFromRoot;
        public float rootYOnGround;
        public float safeStepHeight;
        public float safePlatformWidth;
        public float guideCharacterSize;
        public float gateHeight;
    }

    private struct StageAssets
    {
        public GameObject enemy;
        public GameObject breakableWall;
        public GameObject checkpoint;
        public GameObject fallingPlatform;
        public GameObject door;
        public GameObject goal;
        public GameObject hitSwitch;
        public GameObject magnet;
        public GameObject movingPlatform;
        public GameObject respawnZone;
        public GameObject spikeTrap;
        public GameObject weightSwitch;

        public bool IsComplete =>
            enemy != null &&
            breakableWall != null &&
            checkpoint != null &&
            fallingPlatform != null &&
            door != null &&
            goal != null &&
            hitSwitch != null &&
            magnet != null &&
            movingPlatform != null &&
            respawnZone != null &&
            spikeTrap != null &&
            weightSwitch != null;
    }
}
#endif
